// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcess(arg1:number):Promise<string>;

export function SendToggleEvent(arg1:string):Promise<void>;
